# BULID DEV ##
version: "3.7"
services:
  mysql-oncology-med:
    container_name: mysql-oncology-med
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./server/.env.development
    volumes:
      - mysql_data:/var/lib/mysql

  oncology-med-be:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: oncology-med-be
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always
    env_file:
      - ./server/.env.development
    depends_on:
      - mysql-oncology-med
    external_links:
      - mysql-oncology-med

  oncology-med-fe:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: oncology-med-fe
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.development
    volumes:
      - ./client:/app

volumes:
  mysql_data:
# services:
#   doctor-wattanvej:
#     platform: linux/amd64
#     build:
#       dockerfile: Dockerfile.dev
#       context: .
#     ports:
#       - "3002:3002"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     restart: always
#     env_file:
#       - development.env
#     external_links:
#       - socket-wattanavej
#     networks:
#       - socket-wattanavej_default
# networks:
#   socket-wattanavej_default:
#     external: true
